### ISSUE TITLE
Youtube API

### ISSUE THREAD

**Issue by villyaraujo** [lewhunt/mixmotion#2]
Is it possible to use the Youtube API?

**Comment by lewhunt** [comment]
Hi, currently no, it only supports Mixcloud. 

I'll let you know if and when it gets upgraded to support other services. Definitely doable but needs some refactoring.

In the meantime, check out my other repo [react-tv-player](https://github.com/lewhunt/react-tv-player) as that supports Youtube and it might suit your needs. It doesn't have the visual effects, but has a similar UI on big screen devices.
